### ISSUE TITLE
Tutorial for working AD or Azure AD

### ISSUE THREAD

**Issue by ghost** [Nike-Inc/harbormaster#1]
Hi,

Thanks for open-sourcing harbormaster. I was wondering if there is a step by step guide on how to enable this with AD or Azure AD. 
I was comparing this with [dex](https://github.com/coreos/dex) and [keystone](https://platform9.com/blog/keystone-authentication-ad/) . 
Any pointers?

**Comment by thomastaylor312** [comment]
@ashishkulk We could definitely make this clearer. Currently it supports the MS Graph API (which I think works with Azure AD) and there is a link on how to get working with the MS Graph API in the README. If you wanted to do a direct AD query, that could be contributed as a `Getter`.

As for how this compares to Dex or Keystone, Harbormaster is not supposed to be an identity provider like Dex and Keystone are. It will integrate with any OIDC provider and validate a token from them and then fetch groups from another source (this helped us get around limitations with which groups we had available with our OIDC provider and the limitation on the number of groups that fit in a JWT). We also had plans to enable Harbormaster to fetch groups from multiple sources in the future.

If you'd like to chat in realtime, feel free to hit me up on the Kubernetes slack (handle is `oftaylor`)

**Comment by ghost** [comment]
Thanks @thomastaylor312 for your prompt response. I will surely try the MS Graph API and slack you if I run into problems.
