### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by pierluigilenoci** [Nike-Inc/harbormaster#2]
Hi guys, has this project been abandoned, or hasn't it been publicly released after the first release? 

@thomastaylor312 @rji @mootpt @bwynsm

**Comment by thomastaylor312** [comment]
Insofar as I know, this isn't being used, but I don't think many of the people tagged here work for Nike anymore

**Comment by pierluigilenoci** [comment]
According to GitHub history Ben Wynsma (@bwynsm) is still working for Nike. 😛

**Comment by bwynsm** [comment]
Still working for Nike - have to admit that I have not even seen this repository before :) I was made contributor across open source projects to help oversee the gimme-aws-creds project.

**Comment by pierluigilenoci** [comment]
@bwynsm do you have any way to let me know if this project is still supported?
I was hoping it was still supported internally but the public repo was not updated.
It would be interesting to use but it has been frozen for 4 years and it scares me a bit. 😛

**Comment by pierluigilenoci** [comment]
Ok, it is abandoned.
